Disable the mkv plugin
Compiling this plugin fails with errors like these:

matroska_segment.cpp:1249:5: error: variable 'BlockGetHandler_l3_tag' is used but
      not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage
    MKV_SWITCH_CREATE( EbmlTypeDispatcher, BlockGetHandler_l3, BlockPayload )
    ^